services:
  vnc:
    tty: true
    stdin_open: true
    image: vnc
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c /root/start-vnc
    ports:
      - '5901:5900'
    volumes:
      - ./shared:/root/shared:delegated
